-- +goose Up
-- Pier photos (D-19): the object key is always server-generated by
-- PresignPierPhoto in the exact form "piers/<uuidv7>.(jpg|png|webp)" — the
-- check constraint is the belt-and-suspenders DB-level enforcement of the
-- same regexp domain.Pier.Validate applies (D-14).
alter table piers add column photo_key text not null default ''
  check (photo_key = '' or photo_key ~ '^piers/[0-9a-f-]{36}\.(jpg|png|webp)$');

-- +goose Down
alter table piers drop column photo_key;
