// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boats.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBoats = `-- name: ListBoats :many
select id, operator_id, name, default_capacity, status, created_at, updated_at from boats order by name, id
`

func (q *Queries) ListBoats(ctx context.Context) ([]Boat, error) {
	rows, err := q.db.Query(ctx, listBoats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Boat
	for rows.Next() {
		var i Boat
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Name,
			&i.DefaultCapacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBoat = `-- name: UpsertBoat :one
insert into boats (id, operator_id, name, default_capacity, status)
values ($1, $2, $3, $4, $5)
on conflict (id) do update
  set name = excluded.name,
      default_capacity = excluded.default_capacity,
      status = excluded.status,
      updated_at = now()
  where boats.operator_id = excluded.operator_id
returning id, operator_id, name, default_capacity, status, created_at, updated_at
`

type UpsertBoatParams struct {
	ID              pgtype.UUID
	OperatorID      pgtype.UUID
	Name            string
	DefaultCapacity int32
	Status          string
}

func (q *Queries) UpsertBoat(ctx context.Context, arg UpsertBoatParams) (Boat, error) {
	row := q.db.QueryRow(ctx, upsertBoat,
		arg.ID,
		arg.OperatorID,
		arg.Name,
		arg.DefaultCapacity,
		arg.Status,
	)
	var i Boat
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Name,
		&i.DefaultCapacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
