// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Boat struct {
	ID              pgtype.UUID
	OperatorID      pgtype.UUID
	Name            string
	DefaultCapacity int32
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	HomePierID      pgtype.UUID
	ArchivedAt      pgtype.Timestamptz
}

type Operator struct {
	ID         pgtype.UUID
	Name       string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	Topic       string
	AggregateID string
	EventType   string
	Payload     []byte
	Traceparent string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Pier struct {
	ID         pgtype.UUID
	OperatorID pgtype.UUID
	NameTh     string
	NameEn     string
	Lat        float64
	Lng        float64
	Address    string
	OpensAt    pgtype.Time
	ClosesAt   pgtype.Time
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	EventType   string
	ProcessedAt pgtype.Timestamptz
}

type Route struct {
	ID                 pgtype.UUID
	OperatorID         pgtype.UUID
	PierFromID         pgtype.UUID
	PierToID           pgtype.UUID
	DurationMinutes    int32
	CancellationPolicy []byte
	ArchivedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type RoutePrice struct {
	RouteID       pgtype.UUID
	TicketType    string
	AmountSatang  int64
	EffectiveFrom pgtype.Date
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
