// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOperator = `-- name: ArchiveOperator :one
update operators
set archived_at = coalesce(archived_at, now()),
    updated_at = now()
where id = $1
returning id, name, archived_at, created_at, updated_at
`

func (q *Queries) ArchiveOperator(ctx context.Context, id pgtype.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, archiveOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActivePiersForOperator = `-- name: CountActivePiersForOperator :one
select count(*) from piers where operator_id = $1 and archived_at is null
`

func (q *Queries) CountActivePiersForOperator(ctx context.Context, operatorID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePiersForOperator, operatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOperator = `-- name: GetOperator :one
select id, name, archived_at, created_at, updated_at from operators where id = $1
`

func (q *Queries) GetOperator(ctx context.Context, id pgtype.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorForShare = `-- name: GetOperatorForShare :one
select id, name, archived_at, created_at, updated_at from operators where id = $1 for share
`

func (q *Queries) GetOperatorForShare(ctx context.Context, id pgtype.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorForShare, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorForUpdate = `-- name: GetOperatorForUpdate :one
select id, name, archived_at, created_at, updated_at from operators where id = $1 for update
`

func (q *Queries) GetOperatorForUpdate(ctx context.Context, id pgtype.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorForUpdate, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperatorsScoped = `-- name: ListOperatorsScoped :many
select id, name, archived_at, created_at, updated_at from operators
where $1::bool or id = $2
order by name, id
`

type ListOperatorsScopedParams struct {
	AllScope   bool
	OperatorID pgtype.UUID
}

func (q *Queries) ListOperatorsScoped(ctx context.Context, arg ListOperatorsScopedParams) ([]Operator, error) {
	rows, err := q.db.Query(ctx, listOperatorsScoped, arg.AllScope, arg.OperatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOperator = `-- name: UpsertOperator :one
insert into operators (id, name)
values ($1, $2)
on conflict (id) do update
  set name = excluded.name,
      updated_at = now()
  where operators.archived_at is null
returning id, name, archived_at, created_at, updated_at
`

type UpsertOperatorParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertOperator(ctx context.Context, arg UpsertOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, upsertOperator, arg.ID, arg.Name)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
