// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: piers.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePier = `-- name: ArchivePier :one
update piers
set archived_at = coalesce(archived_at, now()),
    updated_at = now()
where id = $1
returning id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at
`

func (q *Queries) ArchivePier(ctx context.Context, id pgtype.UUID) (Pier, error) {
	row := q.db.QueryRow(ctx, archivePier, id)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPierForShare = `-- name: GetPierForShare :one
select id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at from piers
where id = $1
for share
`

func (q *Queries) GetPierForShare(ctx context.Context, id pgtype.UUID) (Pier, error) {
	row := q.db.QueryRow(ctx, getPierForShare, id)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPierForShareScoped = `-- name: GetPierForShareScoped :one
select id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at from piers
where id = $1
  and ($2::bool or (operator_id = $3 and id = any($4::uuid[])))
for share
`

type GetPierForShareScopedParams struct {
	ID         pgtype.UUID
	AllScope   bool
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
}

func (q *Queries) GetPierForShareScoped(ctx context.Context, arg GetPierForShareScopedParams) (Pier, error) {
	row := q.db.QueryRow(ctx, getPierForShareScoped,
		arg.ID,
		arg.AllScope,
		arg.OperatorID,
		arg.PierIds,
	)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPierForUpdateScoped = `-- name: GetPierForUpdateScoped :one
select id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at from piers
where id = $1
  and ($2::bool or (operator_id = $3 and id = any($4::uuid[])))
for update
`

type GetPierForUpdateScopedParams struct {
	ID         pgtype.UUID
	AllScope   bool
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
}

func (q *Queries) GetPierForUpdateScoped(ctx context.Context, arg GetPierForUpdateScopedParams) (Pier, error) {
	row := q.db.QueryRow(ctx, getPierForUpdateScoped,
		arg.ID,
		arg.AllScope,
		arg.OperatorID,
		arg.PierIds,
	)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPier = `-- name: InsertPier :one
insert into piers (id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at
`

type InsertPierParams struct {
	ID         pgtype.UUID
	OperatorID pgtype.UUID
	NameTh     string
	NameEn     string
	Lat        float64
	Lng        float64
	Address    string
	OpensAt    pgtype.Time
	ClosesAt   pgtype.Time
}

func (q *Queries) InsertPier(ctx context.Context, arg InsertPierParams) (Pier, error) {
	row := q.db.QueryRow(ctx, insertPier,
		arg.ID,
		arg.OperatorID,
		arg.NameTh,
		arg.NameEn,
		arg.Lat,
		arg.Lng,
		arg.Address,
		arg.OpensAt,
		arg.ClosesAt,
	)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPiersAdmin = `-- name: ListPiersAdmin :many
select id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at from piers
where ($1::bool and ($2::uuid is null or operator_id = $2::uuid))
   or (not $1::bool and operator_id = $3 and id = any($4::uuid[]))
order by name_th, id
`

type ListPiersAdminParams struct {
	AllScope         bool
	FilterOperatorID pgtype.UUID
	OperatorID       pgtype.UUID
	PierIds          []pgtype.UUID
}

func (q *Queries) ListPiersAdmin(ctx context.Context, arg ListPiersAdminParams) ([]Pier, error) {
	rows, err := q.db.Query(ctx, listPiersAdmin,
		arg.AllScope,
		arg.FilterOperatorID,
		arg.OperatorID,
		arg.PierIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pier
	for rows.Next() {
		var i Pier
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.NameTh,
			&i.NameEn,
			&i.Lat,
			&i.Lng,
			&i.Address,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPiersPublic = `-- name: ListPiersPublic :many
select id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at from piers
where archived_at is null
order by name_th, id
`

func (q *Queries) ListPiersPublic(ctx context.Context) ([]Pier, error) {
	rows, err := q.db.Query(ctx, listPiersPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pier
	for rows.Next() {
		var i Pier
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.NameTh,
			&i.NameEn,
			&i.Lat,
			&i.Lng,
			&i.Address,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePier = `-- name: UpdatePier :one
update piers
set name_th = $2,
    name_en = $3,
    lat = $4,
    lng = $5,
    address = $6,
    opens_at = $7,
    closes_at = $8,
    updated_at = now()
where id = $1
returning id, operator_id, name_th, name_en, lat, lng, address, opens_at, closes_at, archived_at, created_at, updated_at
`

type UpdatePierParams struct {
	ID       pgtype.UUID
	NameTh   string
	NameEn   string
	Lat      float64
	Lng      float64
	Address  string
	OpensAt  pgtype.Time
	ClosesAt pgtype.Time
}

func (q *Queries) UpdatePier(ctx context.Context, arg UpdatePierParams) (Pier, error) {
	row := q.db.QueryRow(ctx, updatePier,
		arg.ID,
		arg.NameTh,
		arg.NameEn,
		arg.Lat,
		arg.Lng,
		arg.Address,
		arg.OpensAt,
		arg.ClosesAt,
	)
	var i Pier
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.NameTh,
		&i.NameEn,
		&i.Lat,
		&i.Lng,
		&i.Address,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
