// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRouteForUpdateScoped = `-- name: GetRouteForUpdateScoped :one
select routes.id, routes.operator_id, routes.pier_from_id, routes.pier_to_id, routes.duration_minutes, routes.cancellation_policy, routes.archived_at, routes.created_at, routes.updated_at from routes
where routes.id = $1
  and ($2::bool or (routes.operator_id = $3 and routes.pier_from_id = any($4::uuid[])))
for update of routes
`

type GetRouteForUpdateScopedParams struct {
	ID         pgtype.UUID
	AllScope   bool
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
}

func (q *Queries) GetRouteForUpdateScoped(ctx context.Context, arg GetRouteForUpdateScopedParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteForUpdateScoped,
		arg.ID,
		arg.AllScope,
		arg.OperatorID,
		arg.PierIds,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PierFromID,
		&i.PierToID,
		&i.DurationMinutes,
		&i.CancellationPolicy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :one
insert into routes (id, operator_id, pier_from_id, pier_to_id, duration_minutes, cancellation_policy)
values ($1, $2, $3, $4, $5, $6)
returning id, operator_id, pier_from_id, pier_to_id, duration_minutes, cancellation_policy, archived_at, created_at, updated_at
`

type InsertRouteParams struct {
	ID                 pgtype.UUID
	OperatorID         pgtype.UUID
	PierFromID         pgtype.UUID
	PierToID           pgtype.UUID
	DurationMinutes    int32
	CancellationPolicy []byte
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.ID,
		arg.OperatorID,
		arg.PierFromID,
		arg.PierToID,
		arg.DurationMinutes,
		arg.CancellationPolicy,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PierFromID,
		&i.PierToID,
		&i.DurationMinutes,
		&i.CancellationPolicy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutesAdmin = `-- name: ListRoutesAdmin :many
select routes.id, routes.operator_id, routes.pier_from_id, routes.pier_to_id, routes.duration_minutes, routes.cancellation_policy, routes.archived_at, routes.created_at, routes.updated_at from routes
join piers pf on pf.id = routes.pier_from_id
join piers pt on pt.id = routes.pier_to_id
where ($1::bool and ($2::uuid is null or routes.operator_id = $2::uuid))
   or (not $1::bool and routes.operator_id = $3 and routes.pier_from_id = any($4::uuid[]))
order by pf.name_th, pt.name_th, routes.id
`

type ListRoutesAdminParams struct {
	AllScope         bool
	FilterOperatorID pgtype.UUID
	OperatorID       pgtype.UUID
	PierIds          []pgtype.UUID
}

func (q *Queries) ListRoutesAdmin(ctx context.Context, arg ListRoutesAdminParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesAdmin,
		arg.AllScope,
		arg.FilterOperatorID,
		arg.OperatorID,
		arg.PierIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.PierFromID,
			&i.PierToID,
			&i.DurationMinutes,
			&i.CancellationPolicy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesPublic = `-- name: ListRoutesPublic :many
select routes.id, routes.operator_id, routes.pier_from_id, routes.pier_to_id, routes.duration_minutes, routes.cancellation_policy, routes.archived_at, routes.created_at, routes.updated_at from routes
join piers pf on pf.id = routes.pier_from_id
join piers pt on pt.id = routes.pier_to_id
where routes.archived_at is null and pf.archived_at is null and pt.archived_at is null
order by pf.name_th, pt.name_th, routes.id
`

func (q *Queries) ListRoutesPublic(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.PierFromID,
			&i.PierToID,
			&i.DurationMinutes,
			&i.CancellationPolicy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
update routes
set pier_to_id = $2,
    duration_minutes = $3,
    cancellation_policy = $4,
    updated_at = now()
where id = $1
returning id, operator_id, pier_from_id, pier_to_id, duration_minutes, cancellation_policy, archived_at, created_at, updated_at
`

type UpdateRouteParams struct {
	ID                 pgtype.UUID
	PierToID           pgtype.UUID
	DurationMinutes    int32
	CancellationPolicy []byte
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.PierToID,
		arg.DurationMinutes,
		arg.CancellationPolicy,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PierFromID,
		&i.PierToID,
		&i.DurationMinutes,
		&i.CancellationPolicy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
