// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: route_prices.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCurrentPrices = `-- name: ListCurrentPrices :many
select distinct on (route_id, ticket_type)
  route_id, ticket_type, amount_satang, effective_from
from route_prices
where route_id = any($1::uuid[])
  and effective_from <= $2::date
order by route_id, ticket_type, effective_from desc
`

type ListCurrentPricesParams struct {
	RouteIds []pgtype.UUID
	OnDate   pgtype.Date
}

type ListCurrentPricesRow struct {
	RouteID       pgtype.UUID
	TicketType    string
	AmountSatang  int64
	EffectiveFrom pgtype.Date
}

func (q *Queries) ListCurrentPrices(ctx context.Context, arg ListCurrentPricesParams) ([]ListCurrentPricesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentPrices, arg.RouteIds, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentPricesRow
	for rows.Next() {
		var i ListCurrentPricesRow
		if err := rows.Scan(
			&i.RouteID,
			&i.TicketType,
			&i.AmountSatang,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePrices = `-- name: ListRoutePrices :many
select route_id, ticket_type, amount_satang, effective_from, created_at, updated_at from route_prices
where route_id = $1
order by effective_from desc, ticket_type
`

func (q *Queries) ListRoutePrices(ctx context.Context, routeID pgtype.UUID) ([]RoutePrice, error) {
	rows, err := q.db.Query(ctx, listRoutePrices, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutePrice
	for rows.Next() {
		var i RoutePrice
		if err := rows.Scan(
			&i.RouteID,
			&i.TicketType,
			&i.AmountSatang,
			&i.EffectiveFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutePrice = `-- name: UpsertRoutePrice :one
insert into route_prices (route_id, ticket_type, amount_satang, effective_from)
values ($1, $2, $3, $4)
on conflict (route_id, ticket_type, effective_from) do update
  set amount_satang = excluded.amount_satang,
      updated_at = now()
returning route_id, ticket_type, amount_satang, effective_from, created_at, updated_at
`

type UpsertRoutePriceParams struct {
	RouteID       pgtype.UUID
	TicketType    string
	AmountSatang  int64
	EffectiveFrom pgtype.Date
}

func (q *Queries) UpsertRoutePrice(ctx context.Context, arg UpsertRoutePriceParams) (RoutePrice, error) {
	row := q.db.QueryRow(ctx, upsertRoutePrice,
		arg.RouteID,
		arg.TicketType,
		arg.AmountSatang,
		arg.EffectiveFrom,
	)
	var i RoutePrice
	err := row.Scan(
		&i.RouteID,
		&i.TicketType,
		&i.AmountSatang,
		&i.EffectiveFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
