// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	Topic       string
	AggregateID string
	EventType   string
	Payload     []byte
	Traceparent string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Ping struct {
	ID         pgtype.UUID
	OperatorID pgtype.UUID
	Note       string
	CreatedAt  pgtype.Timestamptz
	AckedAt    pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	EventType   string
	ProcessedAt pgtype.Timestamptz
}
