// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackPing = `-- name: AckPing :execrows
update pings set acked_at = now() where id = $1 and acked_at is null
`

func (q *Queries) AckPing(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, ackPing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPing = `-- name: GetPing :one
select id, operator_id, note, created_at, acked_at from pings where id = $1
`

func (q *Queries) GetPing(ctx context.Context, id pgtype.UUID) (Ping, error) {
	row := q.db.QueryRow(ctx, getPing, id)
	var i Ping
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Note,
		&i.CreatedAt,
		&i.AckedAt,
	)
	return i, err
}

const insertPing = `-- name: InsertPing :one
insert into pings (id, operator_id, note)
values ($1, $2, $3)
returning id, operator_id, note, created_at, acked_at
`

type InsertPingParams struct {
	ID         pgtype.UUID
	OperatorID pgtype.UUID
	Note       string
}

func (q *Queries) InsertPing(ctx context.Context, arg InsertPingParams) (Ping, error) {
	row := q.db.QueryRow(ctx, insertPing, arg.ID, arg.OperatorID, arg.Note)
	var i Ping
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Note,
		&i.CreatedAt,
		&i.AckedAt,
	)
	return i, err
}
