// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boats.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBoat = `-- name: GetBoat :one
select boat_id, operator_id, default_capacity, status, updated_at from boats where boat_id = $1
`

func (q *Queries) GetBoat(ctx context.Context, boatID pgtype.UUID) (Boat, error) {
	row := q.db.QueryRow(ctx, getBoat, boatID)
	var i Boat
	err := row.Scan(
		&i.BoatID,
		&i.OperatorID,
		&i.DefaultCapacity,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBoatProjection = `-- name: UpsertBoatProjection :exec
insert into boats (boat_id, operator_id, default_capacity, status)
values ($1, $2, $3, $4)
on conflict (boat_id) do update
  set operator_id      = excluded.operator_id,
      default_capacity = excluded.default_capacity,
      status           = excluded.status,
      updated_at       = now()
`

type UpsertBoatProjectionParams struct {
	BoatID          pgtype.UUID
	OperatorID      pgtype.UUID
	DefaultCapacity int32
	Status          string
}

func (q *Queries) UpsertBoatProjection(ctx context.Context, arg UpsertBoatProjectionParams) error {
	_, err := q.db.Exec(ctx, upsertBoatProjection,
		arg.BoatID,
		arg.OperatorID,
		arg.DefaultCapacity,
		arg.Status,
	)
	return err
}
