// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Boat struct {
	BoatID          pgtype.UUID
	OperatorID      pgtype.UUID
	DefaultCapacity int32
	Status          string
	UpdatedAt       pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	Topic       string
	AggregateID string
	EventType   string
	Payload     []byte
	Traceparent string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	EventType   string
	ProcessedAt pgtype.Timestamptz
}
