// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID          int64
	EventID     pgtype.UUID
	Topic       string
	AggregateID string
	EventType   string
	Payload     []byte
	Traceparent string
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type ProcessedEvent struct {
	EventID     pgtype.UUID
	EventType   string
	ProcessedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID         pgtype.UUID
	Email      pgtype.Text
	Phone      pgtype.Text
	Name       string
	Role       string
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
	DisabledAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
