// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerByEmail = `-- name: InsertCustomerByEmail :one
insert into users (id, email, role)
values ($1, $2, 'customer')
on conflict (email) do nothing
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type InsertCustomerByEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) InsertCustomerByEmail(ctx context.Context, arg InsertCustomerByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, insertCustomerByEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerByPhone = `-- name: InsertCustomerByPhone :one
insert into users (id, phone, role)
values ($1, $2, 'customer')
on conflict (phone) do nothing
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type InsertCustomerByPhoneParams struct {
	ID    pgtype.UUID
	Phone pgtype.Text
}

func (q *Queries) InsertCustomerByPhone(ctx context.Context, arg InsertCustomerByPhoneParams) (User, error) {
	row := q.db.QueryRow(ctx, insertCustomerByPhone, arg.ID, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
