// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users where phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerByEmail = `-- name: InsertCustomerByEmail :one
insert into users (id, email, role)
values ($1, $2, 'customer')
on conflict (email) do nothing
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type InsertCustomerByEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) InsertCustomerByEmail(ctx context.Context, arg InsertCustomerByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, insertCustomerByEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerByPhone = `-- name: InsertCustomerByPhone :one
insert into users (id, phone, role)
values ($1, $2, 'customer')
on conflict (phone) do nothing
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type InsertCustomerByPhoneParams struct {
	ID    pgtype.UUID
	Phone pgtype.Text
}

func (q *Queries) InsertCustomerByPhone(ctx context.Context, arg InsertCustomerByPhoneParams) (User, error) {
	row := q.db.QueryRow(ctx, insertCustomerByPhone, arg.ID, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStaffUser = `-- name: InsertStaffUser :one
insert into users (id, email, name, role, operator_id, pier_ids)
values ($1, $2, $3, $4, $5, $6)
on conflict (email) do nothing
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type InsertStaffUserParams struct {
	ID         pgtype.UUID
	Email      pgtype.Text
	Name       string
	Role       string
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
}

func (q *Queries) InsertStaffUser(ctx context.Context, arg InsertStaffUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertStaffUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.OperatorID,
		arg.PierIds,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffUsers = `-- name: ListStaffUsers :many
select id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at from users
where role <> 'customer'
  and ($1::uuid is null or operator_id = $1::uuid)
order by email, id
`

func (q *Queries) ListStaffUsers(ctx context.Context, operatorID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listStaffUsers, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.Role,
			&i.OperatorID,
			&i.PierIds,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteCustomerToStaff = `-- name: PromoteCustomerToStaff :one
update users
set role = $2, operator_id = $3, pier_ids = $4, name = $5, updated_at = now()
where email = $1 and role = 'customer'
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type PromoteCustomerToStaffParams struct {
	Email      pgtype.Text
	Role       string
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
	Name       string
}

func (q *Queries) PromoteCustomerToStaff(ctx context.Context, arg PromoteCustomerToStaffParams) (User, error) {
	row := q.db.QueryRow(ctx, promoteCustomerToStaff,
		arg.Email,
		arg.Role,
		arg.OperatorID,
		arg.PierIds,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserDisabledAt = `-- name: SetUserDisabledAt :one
update users
set disabled_at = case when $2::bool then now() else null end, updated_at = now()
where id = $1 and role in ('staff', 'pier_admin')
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type SetUserDisabledAtParams struct {
	ID       pgtype.UUID
	Disabled bool
}

func (q *Queries) SetUserDisabledAt(ctx context.Context, arg SetUserDisabledAtParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDisabledAt, arg.ID, arg.Disabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStaffUser = `-- name: UpdateStaffUser :one
update users
set name = $2, role = $3, operator_id = $4, pier_ids = $5, updated_at = now()
where id = $1 and role in ('staff', 'pier_admin')
returning id, email, phone, name, role, operator_id, pier_ids, disabled_at, created_at, updated_at
`

type UpdateStaffUserParams struct {
	ID         pgtype.UUID
	Name       string
	Role       string
	OperatorID pgtype.UUID
	PierIds    []pgtype.UUID
}

func (q *Queries) UpdateStaffUser(ctx context.Context, arg UpdateStaffUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateStaffUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.OperatorID,
		arg.PierIds,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.OperatorID,
		&i.PierIds,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSuperAdmin = `-- name: UpsertSuperAdmin :one
insert into users (id, email, role)
values ($1, $2, 'super_admin')
on conflict (email) do update set
  role = 'super_admin', operator_id = null, pier_ids = '{}', disabled_at = null, updated_at = now()
returning id, (xmax = 0) as inserted
`

type UpsertSuperAdminParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type UpsertSuperAdminRow struct {
	ID       pgtype.UUID
	Inserted bool
}

func (q *Queries) UpsertSuperAdmin(ctx context.Context, arg UpsertSuperAdminParams) (UpsertSuperAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertSuperAdmin, arg.ID, arg.Email)
	var i UpsertSuperAdminRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}
